// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJTTN4GmByotQuyo-sEhwo2nCkwk3_mlQ',
    appId: '1:127120738889:web:7ff185dde64dbf68378d98',
    messagingSenderId: '127120738889',
    projectId: 'toutiebudget',
    authDomain: 'toutiebudget.firebaseapp.com',
    storageBucket: 'toutiebudget.appspot.com',
    measurementId: 'G-SBW8BL2C97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZv_g42zqQCa2Sfyjp2lOHUCGl_38NeA',
    appId: '1:127120738889:android:58d74af9b314105b378d98',
    messagingSenderId: '127120738889',
    projectId: 'toutiebudget',
    storageBucket: 'toutiebudget.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789012:ios:abcdefghijklmnop',
    messagingSenderId: '123456789012',
    projectId: 'toutie-budget',
    storageBucket: 'toutie-budget.appspot.com',
    iosBundleId: 'com.xburnsx.toutieBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789012:ios:abcdefghijklmnop',
    messagingSenderId: '123456789012',
    projectId: 'toutie-budget',
    storageBucket: 'toutie-budget.appspot.com',
    iosBundleId: 'com.xburnsx.toutieBudget',
  );
}
